config/routes.rb
Rails.application.routes.draw do
  resources :dlls
  resources :releases
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dll.rb
class Dll < ApplicationRecord
end

app/models/release.rb
class Release < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def home
    render html: "hello, world!"
  end
end

app/controllers/dlls_controller.rb
class DllsController < ApplicationController
  before_action :set_dll, only: [:show, :edit, :update, :destroy]

  # GET /dlls
  # GET /dlls.json
  def index
    @dlls = Dll.all
  end

  # GET /dlls/1
  # GET /dlls/1.json
  def show
  end

  # GET /dlls/new
  def new
    @dll = Dll.new
  end

  # GET /dlls/1/edit
  def edit
  end

  # POST /dlls
  # POST /dlls.json
  def create
    @dll = Dll.new(dll_params)

    respond_to do |format|
      if @dll.save
        format.html { redirect_to @dll, notice: 'Dll was successfully created.' }
        format.json { render :show, status: :created, location: @dll }
      else
        format.html { render :new }
        format.json { render json: @dll.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dlls/1
  # PATCH/PUT /dlls/1.json
  def update
    respond_to do |format|
      if @dll.update(dll_params)
        format.html { redirect_to @dll, notice: 'Dll was successfully updated.' }
        format.json { render :show, status: :ok, location: @dll }
      else
        format.html { render :edit }
        format.json { render json: @dll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dlls/1
  # DELETE /dlls/1.json
  def destroy
    @dll.destroy
    respond_to do |format|
      format.html { redirect_to dlls_url, notice: 'Dll was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dll
      @dll = Dll.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dll_params
      params.require(:dll).permit(:name, :spec_path)
    end
end

app/controllers/releases_controller.rb
class ReleasesController < ApplicationController
  before_action :set_release, only: [:show, :edit, :update, :destroy]

  # GET /releases
  # GET /releases.json
  def index
    @releases = Release.all
  end

  # GET /releases/1
  # GET /releases/1.json
  def show
  end

  # GET /releases/new
  def new
    @release = Release.new
  end

  # GET /releases/1/edit
  def edit
  end

  # POST /releases
  # POST /releases.json
  def create
    @release = Release.new(release_params)

    respond_to do |format|
      if @release.save
        format.html { redirect_to @release, notice: 'Release was successfully created.' }
        format.json { render :show, status: :created, location: @release }
      else
        format.html { render :new }
        format.json { render json: @release.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /releases/1
  # PATCH/PUT /releases/1.json
  def update
    respond_to do |format|
      if @release.update(release_params)
        format.html { redirect_to @release, notice: 'Release was successfully updated.' }
        format.json { render :show, status: :ok, location: @release }
      else
        format.html { render :edit }
        format.json { render json: @release.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /releases/1
  # DELETE /releases/1.json
  def destroy
    @release.destroy
    respond_to do |format|
      format.html { redirect_to releases_url, notice: 'Release was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_release
      @release = Release.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def release_params
      params.require(:release).permit(:name, :commit_hash)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dlls_helper.rb
module DllsHelper
end

app/helpers/releases_helper.rb
module ReleasesHelper
end

app/views/dlls/_form.html.erb
<%= form_for(dll) do |f| %>
  <% if dll.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dll.errors.count, "error") %> prohibited this dll from being saved:</h2>

      <ul>
      <% dll.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :spec_path %>
    <%= f.text_field :spec_path %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dlls/edit.html.erb
<h1>Editing Dll</h1>

<%= render 'form', dll: @dll %>

<%= link_to 'Show', @dll %> |
<%= link_to 'Back', dlls_path %>

app/views/dlls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dlls</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Spec path</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dlls.each do |dll| %>
      <tr>
        <td><%= dll.name %></td>
        <td><%= dll.spec_path %></td>
        <td><%= link_to 'Show', dll %></td>
        <td><%= link_to 'Edit', edit_dll_path(dll) %></td>
        <td><%= link_to 'Destroy', dll, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dll', new_dll_path %>

app/views/dlls/new.html.erb
<h1>New Dll</h1>

<%= render 'form', dll: @dll %>

<%= link_to 'Back', dlls_path %>

app/views/dlls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dll.name %>
</p>

<p>
  <strong>Spec path:</strong>
  <%= @dll.spec_path %>
</p>

<%= link_to 'Edit', edit_dll_path(@dll) %> |
<%= link_to 'Back', dlls_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dx11tracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/releases/_form.html.erb
<%= form_for(release) do |f| %>
  <% if release.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(release.errors.count, "error") %> prohibited this release from being saved:</h2>

      <ul>
      <% release.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :commit_hash %>
    <%= f.text_field :commit_hash %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/releases/edit.html.erb
<h1>Editing Release</h1>

<%= render 'form', release: @release %>

<%= link_to 'Show', @release %> |
<%= link_to 'Back', releases_path %>

app/views/releases/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Releases</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Commit hash</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @releases.each do |release| %>
      <tr>
        <td><%= release.name %></td>
        <td><%= release.commit_hash %></td>
        <td><%= link_to 'Show', release %></td>
        <td><%= link_to 'Edit', edit_release_path(release) %></td>
        <td><%= link_to 'Destroy', release, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Release', new_release_path %>

app/views/releases/new.html.erb
<h1>New Release</h1>

<%= render 'form', release: @release %>

<%= link_to 'Back', releases_path %>

app/views/releases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @release.name %>
</p>

<p>
  <strong>Commit hash:</strong>
  <%= @release.commit_hash %>
</p>

<%= link_to 'Edit', edit_release_path(@release) %> |
<%= link_to 'Back', releases_path %>